export { default as Login } from './Auths/Login/Login'
export { default as Dashboard } from './PrivateComponents/Dashboard/Dashboard'
export { default as RecruitmentForm } from './PrivateComponents/RecruitmentForm/RecruitmentForm'
export { default as NotFound } from './404/NotFound'
export { default as BOPAttendance } from './PrivateComponents/Dashboard/BOPAttendance/BOPAttendance'